version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!123
    ports:
      - "1433:1433"

  webapi:
    image: mywebapi
    container_name: mywebapi_1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    depends_on:
      - sqlserver
